language: ruby
rvm:
- 2.2.3
before_install: gem install bundler -v 1.10.6
env:
  global:
  - secure: Gdx71duOJjyOa/ejO5FXP6n66Fb7dC4Rzwc/tUAB3rbF9YNsN/uWzW9tr1yjRkk4WAPP3mxR4hmRkStkgABhDMU4Q/NVcJ64klVf6JUeYYwheUz/gpfkn4wQdo2Q9O8KVPZ/WocIMWCMk+l2FnusIljxdx6Fu0yitQUJGrry3VX1liU5xKcBlpZZsb2gcy77+ikXwT3y32uZEWZe+ThfHBryNXTdqxkpMSLfgU+y0j6KCTmH8ce402UBbNXtqj56O2StRzuKf/N5XHqOMJ45iZkG39V1AVL63HbLfE8vg/KrzlWX9pf60EXZUAG2il4NSRFqdGTv2aV/PoxHzKgZzwuL6eoco3vopqauYmczHAzVDCWD8rTBABGBQk5O9nN55WXKl2C+/H7LwSLBkgCAEE2UkUcUSe12DZ9eSzilQXCpAs7owoxeBXLbAGIB5jBYoIdpbOL0KJel+4zGdjvfIgT2tUD4jd/NwoZIPl4Wy8cGbrMhbPCqJ0dr9uvmGS74z6YCaa6fmKlZTgpsyAM2JAbhvRT2tBh964RdIQdTVpE8ug+arGCbfjTRBxAMlA26qSyP5fpkQLGHDuVtsx39qr6PVEjWUjqHMHZcHsS743RbTkgO9aXEtPsM2/HWotHy+G2QtSqi5k7cudBFldr8dDJFObOY9vWifTR9j5rIpt4=
