language: ruby
rvm:
- 2.2.0
before_install: gem install bundler -v 1.10.6
env:
  global:
    secure: nFiSRLqyRVSIfB4HBUdT7NtBN8sTb25SpFa9HUQUv9A9y89RC28fxVV0ZadgWmkBqiqgYGvdhrTOphamCab+k3jSJoTYCQ3kWf7KqCAG0rzz/KtHlMeRwmMJxBEREpe+pmLNoTKg3ezCil9msK0Ru9//A7tiz24CPbb9dSdHBFds+LT0sldcP/s5EDkuX1k+XuW1vzZIBni3uYtjJGmKSvJnpD6ycC9kbahpGvZjpvV3C1KRGFdLE7tFmzgoNRADJPXVAFUXA7hv9KkEXLGfVL81RHTQIJPl6sgCGujaT7JkizyLXQd11Kv19QZABzVtMpQjihO3V3Ye5iZ0bE2P4OHsI+h85MpPI5KlqF5e/MzgepHL1bYjeRdp8ZNuf7wO9rkWpgSo5eKz1UR4SKfrilG5PHjvOTT3ICAXKOODrp0ughe3GQpn3G+sZrBhkpXMSqN9AuQtE+5jEWRVvcKfm/yzlxtQc+542OBG9Dqy/+KTW6Ea6NoYv5fFY4+uAP0/5MLLpJm5XUbWSSLNBhdEKvvTo5ADCczjVfhgIN9fNo8uDQ0EwrfkiiQnTxOzLijdgmAoYpFUnQDs0ulf2HL8wW1bZiXwimcBXttLkyFfiEXI0lwmTP3p6zG7guC1yvSJ5i2AXmGoijaN8FFijZTqsL0r0L1wUzUbCZ+aEvc787U=
