train_speed: "@.MWT.M_T3_1.MRV_TrnSpd_1.MRV_Xv_Trn"
line_current: "@.MWT.CT_CI_T2_1.CI_COP_XI_Ln"
line_voltage: "@.MWT.CT_CI_T2_1.CI_COP_XU_Ln"
traction_brake_achieved: "@.MWT.P_T2_1.PII_DCUM1_XF_TrBrAch"
traction_brake_effort_reference_2: "@.MWT.M_T2_1.MRV_W_PwmRef2"
traction_brake_effort_reference_1: "@.MWT.M_T2_1.MRV_W_PwmRef1"
traction_brake_effort_reference: "@.MWT.M_T2_1.MRV_W_TrBrEffRef"
brake_cylinder_pressure_car_b_bogie_a: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarBBgA"
brake_cylinder_pressure_car_b_bogie_d: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarBBgD"
