train_run_distance: "MSV_Xs_TrnRnDstTot"
this_cab_active: "@.MWT.R_T3_1.RCV_S_ThisCabAct"
atp_worst_case_forward_location: "@.MWT.S_ATC_T4_1.SSV_X_AtpWrstFwLocSegId"
atp_worst_case_forward_location_offset: "@.MWT.S_ATC_T4_1.SSV_X_AtpWrstFwLocOffs"
train_speed: "@.MWT.M_T3_1.MRV_TrnSpd_1.MRV_Xv_Trn"
line_voltage: "@.MWT.CT_CI_T2_1.CI_COP_XU_Ln"
line_current: "@.MWT.CT_CI_T2_1.CI_COP_XI_Ln"
hscb_close: "@.MWT.H_T2_1.DX54_Out2_C_HscbCl"
order_hscb_to_open_from_cop: "@.MWT.H_T3_1.HCV_C_CopHscbOp"
cop_is_ok_for_supervision: "@.MWT.CT_CI_T3_1.CI_COP_S_CopOk"
mcs_driving_mode_forward: "@.MWT.CT_CI_T3_1.DI13_In5_S_McsDrvMdFw"
mcs_driving_mode_inter: "@.MWT.CT_CI_T3_1.DI13_In4_S_McsDrvMdInter"
mcs_driving_mode_reverse: "@.MWT.CT_CI_T3_1.DI13_In3_S_McsDrvMdRv"
mcs_driving_mode_protected_manual: "@.MWT.CT_CI_T3_1.DI13_In6_S_McsDrvMdPrMan"
mcs_driving_mode_auto: "@.MWT.CT_CI_T3_1.DX17_In7_S_McsDrvMdAuto"
mcs_driving_mode_selected: "@.MWT.M_T4_1.MCV_S_McsDrvMdSd"
actuate_braking: "@.MWT.CT_CI_T2_1.DI20_In9_TrLn_AB"
actuate_motor: "@.MWT.CT_CI_T2_1.DI20_In10_TrLn_AM"
tr_br_effort_reference_1: "@.MWT.M_T2_1.MRV_W_PwmRef1"
tr_br_effort_reference_2: "@.MWT.M_T2_1.MRV_W_PwmRef2"
traction_brake_effort_reference: "@.MWT.M_T2_1.MRV_W_TrBrEffRef"
emergency_brake_applied: "@.MWT.B_T3_1.BSV_S_EmBrApl"
brake_cylinder_pressure_car_a_bogie_a: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarABgA"
brake_cylinder_pressure_car_a_bogie_d: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarABgD"
brake_cylinder_pressure_car_b_bogie_a: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarBBgA"
brake_cylinder_pressure_car_b_bogie_d: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarBBgD"
brake_cylinder_pressure_car_c_bogie_a: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarCBgA"
brake_cylinder_pressure_car_c_bogie_d: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarCBgD"
brake_cylinder_pressure_car_d_bogie_a: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarDBgA"
brake_cylinder_pressure_car_d_bogie_d: "@.MWT.CT_CI_T3_1.CI_BGW_Wp_BcPrsCarDBgD"
main_reservoir_pressure: "@.MWT.CT_CI_T4_1.CI_BGW_Wp_MnReservoir"
wsp_active: "@.MWT.CT_CI_T3_1.CI_BGW_S_WspAct"
all_doors_closed: "@.MWT.CT_CI_T3_1.DX11_In3_S_AllDrCld"
mcm_state: "@.MWT.P_T3_1.PII_DCUM1_X_McmSt"
mcm_state: "@.MWT.P_T3_1.PII_DCUM2_X_McmSt"
traction_brake_achieved: "@.MWT.P_T2_1.PII_DCUM1_XF_TrBrAch"
actual_chopper_power: "@.MWT.P_T3_1.PII_DCUM1_XP_Cp"
actual_motor_power: "@.MWT.P_T3_1.PII_DCUM1_XP_Mt"
available_dynamic_brake: "@.MWT.P_T3_1.PII_DCUM1_XF_BrAvl"
estimated_brake_resistor_temparature: "@.MWT.P_T4_1.PII_DCUM1_XT_EstBrRs"
estimated_brake_resistor_temparature: "@.MWT.P_T4_1.PII_DCUM2_XT_EstBrRs"
actual_chopper_power: "@.MWT.P_T3_1.PII_DCUM2_XP_Cp"
actual_motor_power: "@.MWT.P_T4_1.PII_DCUM2_XP_Mt"
available_dynamic_brake: "@.MWT.P_T3_1.PII_DCUM2_XF_BrAvl"
dynamic_brake_ok: "@.MWT.P_T2_1.PII_DCUM1_S_DynBrOk"
dynamic_brake_ok: "@.MWT.P_T2_1.PII_DCUM2_S_DynBrOk"
lma_end_location: "@.MWT.CT_CI_T4_1.CI_ATP1_X_LmaEndLocSegId"
lma_end_location_offset: "@.MWT.CT_CI_T4_1.CI_ATP1_X_LmaEndLocOffset"
lma_end_location: "@.MWT.CT_CI_T4_1.CI_ATP2_X_LmaEndLocSegId"
lma_end_location_offset: "@.MWT.CT_CI_T4_1.CI_ATP2_X_LmaEndLocOffset"
ato_start_button_1_pressed: "@.MWT.CT_CI_T3_1.DI13_In7_S_AtoPb1Act"
ato_start_button_2_pressed: "@.MWT.CT_CI_T3_1.DI13_In8_S_AtoPb2Act"
passesnger_load_car_a: "@.MWT.B_T5_1.BRV_X_prctPssngrLdCarA"
passesnger_load_car_b: "@.MWT.B_T5_1.BRV_X_prctPssngrLdCarB"
passesnger_load_car_c: "@.MWT.B_T5_1.BRV_X_prctPssngrLdCarC"
passesnger_load_car_d: "@.MWT.B_T5_1.BRV_X_prctPssngrLdCarD"
passenger_load_to_ato: "@.MWT.B_T5_1.BRV_X_TrnLd"
compressor_start: "@.MWT.A_T4_1.ACV_C_CmprSta"
compressor_motor_running: "@.MWT.A_T4_1.ASV_S_CmprMtRn"
pressure_low_limit: "@.MWT.A_T4_1.ACV_MsCmpr_1.P_Xp_PrsLoLim"
pressure_low_limit: "@.MWT.A_T4_1.ASV_AirPrs_1.P_Xp_PrsLoLim"
sync_all_clocks: "@.MWT.CT_CO_T4_1.CP_C_TrgSncAll"
sync_local_clock: "@.MWT.CT_CO_T4_1.CP_C_TrgSncLc"
sync_master_clock_from_pdp1: "@.MWT.CT_CO_T4_1.CP_C_TrgSncMsPdp1"
sync_master_clock_from_pdp2: "@.MWT.CT_CO_T4_1.CP_C_TrgSncMsPdp2"
sync_pdp_clock: "@.MWT.CT_CO_T4_1.CP_C_TrgSncPdp"
year: "@.MWT.CT_CO_T4_1.CP_X_AnsiYear"
month: "@.MWT.CT_CO_T4_1.CP_X_AnsiMon"
day: "@.MWT.CT_CO_T4_1.CP_X_AnsiDay"
hour: "@.MWT.CT_CO_T4_1.CP_X_AnsiHour"
minute: "@.MWT.CT_CO_T4_1.CP_X_AnsiMin"
second: "@.MWT.CT_CO_T4_1.CP_X_AnsiSec"
train_number: "@.MWT.S_ATC_T4_1.CO_ATO_X_TrnNo"
crew_number: "@.MWT.S_ATC_T4_1.CO_ATO_X_CrwNo"
destination_code: "@.MWT.S_ATC_T4_1.CO_ATO_X_DstntnCode"
train_service_code: "@.MWT.S_ATC_T4_1.CO_ATO_X_TrnSrvCode"
train_fault_report_code: "@.MWT.S_ATC_T4_1.CO_ATO_X_TrnFltRepCode"
train_stock_type: "@.MWT.S_ATC_T4_1.CO_ATO_X_TrnStckTp"
train_unit_number_1st: "@.MWT.S_ATC_T4_1.CO_ATO_X_FrstTrnUntId"
train_unit_number_2nd: "@.MWT.S_ATC_T4_1.CO_ATO_X_SecTrnUntId"
train_mode: "@.MWT.S_ATC_T4_1.CO_ATO_X_TrnMd"
a_car_temperature: "@.MWT.CT_CI_T5_1.AX19_In2_X_AcarTmp"
b_car_temperature: "@.MWT.CT_CI_T5_1.AX19_In4_X_BcarTmp"
c_car_temperature: "@.MWT.CT_CI_T4_1.AX47_In4_X_CcarTmp"
d_car_temperature: "@.MWT.CT_CI_T4_1.AX47_In2_X_DcarTmp"
pv1_temperature: "@.MWT.K_T5_1.KCV_X_PrsVnt1TmpIn"
pv1_temperature: "@.MWT.K_T5_1.KEV_X_PrsVnt1Tmp"
pv2_temperature: "@.MWT.K_T5_1.KEV_X_PrsVnt2Tmp"
